Repository Pre-Onboarding-FE-Team07/wanted-codestates-project-7-7-1, pull requests merged in 2022-03, with the labels that each got.

#9 Feature/8/select type
  src/components/CreateForm/Field.tsx
  src/components/CreateForm/FieldList.tsx
  src/components/CreateForm/FieldTools.tsx
  src/components/CreateForm/FieldTools/CheckBox.tsx
  src/components/CreateForm/FieldTools/Input.tsx
  src/components/CreateForm/FieldTools/Option.tsx
  src/components/CreateForm/FieldTools/OptionList.tsx
  src/components/CreateForm/FieldTools/SelectType.tsx
  src/components/CreateForm/FieldTools/index.ts
  src/components/CreateForm/TextEditor.tsx
  src/components/CreateFormButtonWrap.tsx
  src/components/Field/FieldList.tsx
  src/components/Field/FieldTools/FieldTools.tsx
  src/constants/createForm.ts
  src/context/CreateFormContext.tsx
  src/context/actions/createForm.ts
  src/context/actions/types.ts
  src/context/reducers/createForm.tsx
  src/interfaces/createForm.d.tsx
  src/pages/CreateFormPage.tsx
  tsconfig.json
Labels: enhancement

#11 Feature: 생성된 폼(주어진 json형식에 맞춰서 기능 만들기)
  package-lock.json
  package.json
  src/components/Btn.tsx
  src/components/Form/Agreement.tsx
  src/components/Form/File.tsx
  src/components/Form/Image.tsx
  src/components/Form/Name.tsx
  src/components/Form/Phone.tsx
  src/components/Form/PostCode.tsx
  src/components/Form/SelectBox.tsx
  src/interfaces/button.d.ts
  src/interfaces/user.d.ts
  src/pages/UserDataPage.tsx
  src/pages/WriteFormPage.tsx
  src/styles/global.ts
  src/styles/theme.ts
Labels: enhancement

#13 Feat: 세부 기능 구현 및 Context API 적용
  package-lock.json
  package.json
  public/index.html
  src/components/CreateForm/ButtonWrap.tsx
  src/components/CreateForm/Field.tsx
  src/components/CreateForm/FieldDatas.tsx
  src/components/CreateForm/FieldList.tsx
  src/components/CreateForm/FieldTools.tsx
  src/components/CreateForm/FieldTools/CheckBox.tsx
  src/components/CreateForm/FieldTools/Input.tsx
  src/components/CreateForm/FieldTools/Option.tsx
  src/components/CreateForm/FieldTools/OptionList.tsx
  src/components/CreateForm/FieldTools/SelectType.tsx
  src/components/CreateForm/FieldTools/index.ts
  src/components/CreateForm/Modal.tsx
  src/components/CreateForm/TextEditor.tsx
  src/components/CreateFormButtonWrap.tsx
  src/components/Form/Name.tsx
  src/components/Form/Phone.tsx
  src/components/Form/PostCode.tsx
  src/components/Form/SelectBox.tsx
  src/constants/createForm.ts
  src/context/CreateFormContext.tsx
  src/context/FieldContext.tsx
  src/context/FormDataContext.tsx
  src/context/actions/createForm.ts
  src/context/actions/field.ts
  src/context/actions/types.ts
  src/context/reducers/createForm.tsx
  src/context/reducers/field.tsx
  src/interfaces/createForm.d.tsx
  src/pages/CreateFormPage.tsx
  src/pages/UserDataPage.tsx
  src/pages/WriteFormPage.tsx
  src/styles/global.ts
  tsconfig.json
Labels: enhancement

#16 Feat: FormListContext 생성 및 적용
  package-lock.json
  package.json
  src/App.tsx
  src/components/CreateForm/ButtonWrap.tsx
  src/components/CreateForm/FieldDatas.tsx
  src/components/Field/Field.tsx
  src/components/Field/FieldList.tsx
  src/components/Field/FieldTools/CheckBox.tsx
  src/components/Field/FieldTools/FieldTools.tsx
  src/components/Field/FieldTools/Input.tsx
  src/components/Field/FieldTools/Option.tsx
  src/components/Field/FieldTools/OptionList.tsx
  src/components/Field/FieldTools/SelectType.tsx
  src/components/Field/FieldTools/index.ts
  src/components/Field/TextEditor.tsx
  src/context/FormDataContext.tsx
  src/context/FormListContext.tsx
  src/context/actions/formList.ts
  src/context/actions/types.ts
  src/context/reducers/formList.tsx
  src/interfaces/createForm.d.tsx
  src/interfaces/formList.d.tsx
  src/pages/index.ts
Labels: enhancement

#23 Fix: Type 에러 및 Console 에러 해결
  src/components/Form/File.tsx
  src/components/Form/PostCode.tsx
Labels: bug

#21 Feat: Surge 배포를 위한 action 설정
  .github/workflows/deployment.yml
Labels: documentation, enhancement

#18 Feat: Toast 적용
  package-lock.json
  package.json
  src/components/CreateForm/ButtonWrap.tsx
  src/utils/Toast.tsx
Labels: enhancement

#19 Feat: FormListPage UI구현
  src/components/Main/AddButton.tsx
  src/components/Main/DropdownList.tsx
  src/index.tsx
  src/pages/FormListPage.tsx
Labels: enhancement

#26 Feat: 데이터 입력 시 userList에 추가하기
  src/components/WrtieForm/Agreement.tsx
  src/components/WrtieForm/File.tsx
  src/components/WrtieForm/PostCode.tsx
  src/components/WrtieForm/SelectBox.tsx
  src/constants/user.ts
  src/context/UserDataContext.tsx
  src/context/UserListContext.tsx
  src/context/reducers/userList.ts
  src/interfaces/user.d.ts
  src/pages/UserDataPage.tsx
  src/pages/WriteFormPage.tsx
Labels: enhancement
